### ISSUE TITLE
ARM Template Checker Skips all My ARM Templates

### ISSUE THREAD

**Issue by denhsu** [azsk/DevOpsKit-docs#102]
Hi, 
Great product!  I encountered an issue with ARM Template Checker.  I know the posts says "but it is possible that folder may contain some ARM Template(s) that are not valid or currently not supported by ARM Checker. In this case AzSK ARM Template Checker Task will skip those file(s) and will fail."  

I wonder what kind of ARM templates won't work?

All my ARM templates got skipped:

Skipped file(s): 9
\DV\AppServiceAppSettings_Short.parameters.json
\DV\DV-DV-Teleclaim-AI.parameters.json
\DV\DV-DV-Teleclaim-FCN.parameters.json
\DV\DV-DV-Teleclaim-PLAN.parameters.json
\DV\DV-DV-Teleclaim-WEB.parameters.json
\DV\DV-DV-Teleclaim-WEB_AppSettings.parameters.json
\DV\DV-DV-Teleclaim-WEB_IpRestriction.parameters.json
\DV\DV-DV-Teleclaim-WEB_Slots.parameters.json
\DV\wsdvteleclaim01.parameters.json
--------------------------------------------------------------------------------
One or more files were skipped during the scan. Either the files are invalid as ARM templates or those resource types are currently not supported by this command.
Please verify the files and re-run the command. For files that should not be included in the scan, you can use the '-ExcludeFiles' parameter.

Thanks,
Dennis

**Comment by VishalHaibatpure** [comment]
From names it looks like these are parameter files. Does these files contains resource types details?

You can have a look at ARM templates samples present [here](https://github.com/azsk/DevOpsKit-docs/tree/master/ARMTemplates)

**Comment by denhsu** [comment]
Thanks @VishalHaibatpure my configuration issue. Should not scan those parameter files, but the ARM templates instead.

**Comment by denhsu** [comment]
Hi @VishalHaibatpure, just a feature request, for ARM template check "Exclude Files" option, is it possible to add wildcard (ex. exclude files with *.parameters.json).

Thanks,
Dennis

**Comment by VishalHaibatpure** [comment]
@denhsu : Thanks for suggestion . Wildcard is now support in ARM template check.
