### ISSUE TITLE
How to Setup Our Own Organizational Online Policy URL

### ISSUE THREAD

**Issue by denhsu** [azsk/DevOpsKit-docs#103]
Hi,

For SVT, we want to setup our own organizational online policy URL, so we can choose which rules to scan.  How do you do that with OnlinePolicyStoreUrl?

Is there any sample Policy file we can explore around?

from "AzSKSettings.json file": 
    "EnableAADAuthForOnlinePolicyStore":  false,
    "OnlinePolicyStoreUrl":  "**https://azsdkossep.azureedge.net/$Version/$FileName**",

Thanks,
Dennis

**Comment by VishalHaibatpure** [comment]
Please refer 07 Section of document for customizing AzSK for Org [Link](https://github.com/azsk/DevOpsKit-docs/tree/master/07-Customizing-AzSK-for-your-Org)

**Comment by denhsu** [comment]
Thanks @VishalHaibatpure I will look into 07 Section of document for customizing AzSK for Org Link

**Comment by denhsu** [comment]
Hi @VishalHaibatpure Just a suggestion, i think it is better to add a link to 07 Section of document for customizing AzSK for Org Link when talking about "Step-5: Setup Online Policy URL" in Section 03.  That will be helpful as I was looking section 03 over and over and see if i miss any content on customizing the online policy url.  Thanks!
