### ISSUE TITLE
Untrusted repository

### ISSUE THREAD

**Issue by SychevIgor** [azsk/DevOpsKit-docs#109]
Will be nice, if we will can install everything from trusted repository.

PS C:\Users\username> Install-Module AzSK -Scope CurrentUser

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or
newer to interact with NuGet-based repositories. The NuGet
provider must be available in 'C:\Program
Files\PackageManagement\ProviderAssemblies' or
'C:\Users\username\AppData\Local\PackageManagement\ProviderAs
semblies'. You can also install the NuGet provider by running
 'Install-PackageProvider -Name NuGet -MinimumVersion
2.8.5.201 -Force'. Do you want PowerShellGet to install and
import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y

Untrusted repository
You are installing the modules from an untrusted repository.
If you trust this repository, change its InstallationPolicy
value by running the Set-PSRepository cmdlet. Are you sure
you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend
[?] Help(default is "N"):

**Comment by VishalHaibatpure** [comment]
PS Gallery is open to all contributors, the default mode is ‘Untrusted’. Thus the warning pushes you to make a conscious decision that you are installing a known component from a trustworthy publisher.

**Comment by SychevIgor** [comment]
@VishalHaibatpure thank you for an answer. Let me explain the logic of my customer: we are working on some security features using devopskit, and to install tools we need some checkers from Untrusted source. It's a bit odd from my customer's perspective and they assume, that Microsoft should not frustrate them with such alert.
Customer don't wanna spend hours on verification and making conclusions- they wanna trust to microsoft products.

**Comment by SychevIgor** [comment]
Can we hide this warning using https://docs.microsoft.com/en-us/powershell/module/powershellget/set-psrepository?view=powershell-6 ? 

"This command sets the installation policy for the myInternalSource repository to Trusted, so that users are not prompted before installing modules from that source."
