### ISSUE TITLE
Error with DevOpsKit

### ISSUE THREAD

**Issue by rburrs** [azsk/DevOpsKit-docs#118]
I get the following error when trying to run a security status scan against my subscription:  "Warning: The current user/login context does not have permission to access DevOps Kit control attestations. Due to this, control scan results may not reflect attestation."  

The Execution policy is set to remote signed.  The documentation says to not run Powershell ISE as an administrator, which I didn't.  And I connected to my Azure subscription via Powershell using a Global admin account.  What am I missing?

Thanks!

**Comment by VishalHaibatpure** [comment]
Hi Richard,

Warning is safe guard check for one who is using attestation feature with DevOps kit. 
This warning is now skipped in latest version.  Please install AzSK 3.6.1 and let us know if you still face issue.

**Comment by VishalHaibatpure** [comment]
@rburrs : let us know if you still facing this issue.

**Comment by rburrs** [comment]
Your suggestion resolved the issue.  Thanks!
