### ISSUE TITLE
Being able to define policies

### ISSUE THREAD

**Issue by stephaneey** [azsk/DevOpsKit-docs#120]
Hello,

While this kit is very promising, we'd need to be able to leverage Azure Policies to define what we want to control or not at either subscription level, either resource group level.
When provisioning app services (including the resource group) from an Azure DevOps pipeline, the resource does not exist yet. Therefore, impossible to skip some controls as described here:
https://github.com/azsk/DevOpsKit-docs/tree/master/00c-Addressing-Control-Failures
because this only applies to existing resources.

A good example is the Azure_AppService_AuthN_Use_AAD_for_Client_AuthN control. Most of the times, AAD auth is triggered through middlewares such as OWIN. So, it'd be nice to be able to define a policy that allows to skip that control (and others) for every new resource to come, because we know we work a certain way. 

The alternative right now is to either run assertion on existing resources (so, post-deployment), either to scan ARM templates from within the build or release pipeline, extract the CSV from the logs and create a Skipcontrol file out of it but that's very tedious plus it gives too much power to developers. Enforcing/Relaxing controls through Azure Policies would make much more sense.

**Comment by VishalHaibatpure** [comment]
Please check if [AzSK custom Org policy](https://github.com/azsk/DevOpsKit-docs/tree/master/07-Customizing-AzSK-for-your-Org) feature helps in your case. 
Using this feature you can control behavior of AzSK policies for your Org.

**Comment by stephaneey** [comment]
Hi,

Great, that's exactly what I was looking for. I'm going to give it a try.

Thanks
Best Regards
