### ISSUE TITLE
Unable to find type [GeneratePDF] error when running Get-AzSKSubscriptionSecurityStatus

### ISSUE THREAD

**Issue by wkim-ent** [azsk/DevOpsKit-docs#137]
I get this error when trying to run Get-AzSKSubscriptionSecurityStatus:
Get-AzSKSubscriptionSecurityStatus : Unable to find type [GeneratePDF].
At line:3 char:1
+ Get-AzSKSubscriptionSecurityStatus -SubscriptionId $subId
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (GeneratePDF:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by sapsh-msft** [comment]
Hello, 
We have checked on our side, this functionality is working fine. Can you please clean up and re-install the AzSK module and try again?

**Comment by VishalHaibatpure** [comment]
@wkim-ent : Please try commands with latest AzSK versions. Let us know if you still facing issue.
