### ISSUE TITLE
Is the TreatAsPassed an option at the AZ svt ?

### ISSUE THREAD

**Issue by bilalAchahbar** [azsk/DevOpsKit-docs#141]
Right now i can skip controls with the task Az ARM template checker with the "skip control from file".
But i can't seem to find the option to skip files or in how the documentation said ThreatAsPassed option in the Az security verification test. Is this also an possibility in the Az svt ?

**Comment by rroman81** [comment]
I tried using the AzSK_SVTs task with defined release pipeline variable, TreatAsPassed, and i am still getting failures.  Is that functional?
