### ISSUE TITLE
Can't seem to find a way to use the custom baselines for the ci cd pipeline

### ISSUE THREAD

**Issue by bilalAchahbar** [azsk/DevOpsKit-docs#143]
If i am correctly following [step](https://github.com/azsk/DevOpsKit-docs/blob/master/07-Customizing-AzSK-for-your-Org/Readme.md#steps-2) wil use the controls you give so that you can get a customated Azsk check instead of the default provided of the Azsk team.

I want to do the same thing but in my Azure devops ci/cd pipeline. For now I understand from following [step](https://github.com/azsk/DevOpsKit-docs/blob/master/07-Customizing-AzSK-for-your-Org/Readme.md#using-cicd-extension-with-custom-org-policy) that you add the blob url that was uploaded during following [command](https://github.com/azsk/DevOpsKit-docs/blob/master/07-Customizing-AzSK-for-your-Org/Readme.md#first-time-policy-setup---an-example) but here the custom baseline controls i changed in my local folder from this [step](https://github.com/azsk/DevOpsKit-docs/blob/master/07-Customizing-AzSK-for-your-Org/Readme.md#steps-2) is not being uploaded or being called with the url's in the AzSK.json in the blob. 
So my question is , is it possible to use custom baselinecontrols with an pipeline task and can anyone pls tell me which step I forget or which thing I did wrong ?

**Comment by VishalHaibatpure** [comment]
@bilalAchahbar : Are you able to follow step (iv) in [customizing baseline controls doc](https://github.com/azsk/DevOpsKit-docs/blob/master/07-Customizing-AzSK-for-your-Org/Readme.md#c-creating-a-custom-control-baseline-for-your-org).
 
Below details will help you to run baseline controls in CICD
 
After modifying custom baseline controls in local, you need to update it on policy server either using Install command used during policy setup or Update command.

```PowerShell
#Policy update command for basic setup 
Update-AzSKOrganizationPolicy -SubscriptionId <SubscriptionId> `
   -OrgName "Contoso" `
   -DepartmentName "IT" `
   -PolicyFolderPath "D:\ContosoPolicies"

#Policy update command for custom resource setup 
Update-AzSKOrganizationPolicy -SubscriptionId <SubscriptionId> `
   -OrgName "Contoso-IT" `           
   -ResourceGroupName "Contoso-IT-RG" `
   -StorageAccountName "contosoitsa" `
   -AppInsightName "ContosoITAppInsight" `
   -PolicyFolderPath "D:\ContosoPolicies"
```

Once Policy is updated, you can follow testing steps in your local given in [doc] in fresh PowerShell Session(https://github.com/azsk/DevOpsKit-docs/blob/master/07-Customizing-AzSK-for-your-Org/Readme.md#testing-3). That is try running below command in new PowerShell Session. 

```PowerShell
#Clear state if same PowerShell session is used
Clear-AzSKSessionState
#Run scan command with baseline switch
Get-AzSKAzureServicesSecurityStatus -SubscriptionId <SubscriptionId> -UseBaselineControls
```

Once it works in your local, you can follow below steps to run baseline controls in CICD

1. Add policy url in your pipeline using [step 5](https://github.com/azsk/DevOpsKit-docs/tree/master/03-Security-In-CICD#adding-svts-in-the-release-pipeline)  
2. Add "ExtendedCommand" variable with value "-UseBaselineControls" as giving in doc [here](https://github.com/azsk/DevOpsKit-docs/tree/master/03-Security-In-CICD#advanced-cicd-scanning-capabilities)
3. Run pipeline and validate the logs if its scanning for only baseline controls.

**Comment by bilalAchahbar** [comment]
@VishalHaibatpure   is it possible to mark a control ID as passed for my custom policies.
The only way i found at the moment is to mark the isbaseline control as yes(through the controlsettings) but that doesn't give me a passed value. OR to pass the value false to the enable parameter inside the service/xxxx.json  control id resource and this will just disable the check.

**Comment by VishalHaibatpure** [comment]
@bilalAchahbar : You can address failed controls either following recommendation or attesting it if its not applicable in your scenario. [This](https://github.com/azsk/DevOpsKit-docs/blob/master/00c-Addressing-Control-Failures/Readme.md#control-attestation-1) doc will help you out.

**Comment by bilalAchahbar** [comment]
Thanks , if I'am correctly the only reason to do is, is through powershell comands like [this ](https://github.com/azsk/DevOpsKit-docs/blob/master/00c-Addressing-Control-Failures/Readme.md#bulk-attestation)
So to implement this in azure devops , i need to add a powershell task in my pipeline ?

**Comment by bilalAchahbar** [comment]
A nice way to automate the attesting is inside the service.json files to have one value in the controlid with the value attestation status , so that you can pass notAnIssue, or none , or a value from the[ list](https://github.com/azsk/DevOpsKit-docs/blob/master/00c-Addressing-Control-Failures/Readme.md#how-azsk-determines-the-effective-control-result).

**Comment by bilalAchahbar** [comment]
thanks @VishalHaibatpure 
I studied the documentation you gave me , and ATM i found this solution to add an attesting status to each control i want to modify 
`$subscriptionId = 'xxxxxxxxxxxxxxxxx'
$resourceGroupNames = 'xxxxxxxxxxxxxxxxxxx'
$resourceNames = 'xxxxxxxxxxxxx'
$ControlIds = 'Azure_KeyVault_DP_Identify_Roles'     # You can get this from the CSV file, first column.
$justificationText = 'xxxxxxxxxx'


Get-AzSKAzureServicesSecurityStatus -SubscriptionId $subscriptionId `
               -ResourceGroupNames $resourceGroupNames `
                 -ResourceName $resourceName `
                -ControlIds $ControlIds `
                -ControlsToAttest All `
                -AttestationStatus NotAnIssue `
                -JustificationText $justificationText
                


The problem with this solution , i need to run this command a couple of times to add the attesting status to each control i want to skip ,and then add this to my storage account (with the first install policy or update policy command) so that my CI / CD pipeline can notice the change. But if i have multiple skip controls that i need to pass I have to execute the command multiple times. Is this not possible to add control id's with the attestation status in a file instead of  executing a command multiple times ?
I thought that this is possible in the services json files of each resource type.

                 `
