### ISSUE TITLE
Creating custom policies beyond SVT service polcies

### ISSUE THREAD

**Issue by spbreed** [azsk/DevOpsKit-docs#152]
It seems so far we can only use the custom policies defined under ```\Framework\Configurations\SVT\Services\<service>.json```
https://github.com/azsk/DevOpsKit-docs/tree/master/07-Customizing-AzSK-for-your-Org#c-creating-a-custom-control-baseline-for-your-org
Would it be possible to add custom policies to <service.json>? For example looks at ```VirtualNetwork140``` in ```\Framework\Configurations\SVT\Services\VirtualNetwork.json```, if I need to add custom condition to check list trusted white listed IP's of my organization in inbound NSG rules, would it be possible?

```
 {
      "ControlID": "Azure_VNet_NetSec_Configure_NSG",
      "Description": "NSG should be used for subnets in a virtual network to permit traffic only on required inbound/outbound ports. NSGs should not have a rule to allow any-to-any traffic",
      "Id": "VirtualNetwork140",
      "ControlSeverity": "Medium",
      "Automated": "Yes",
      "MethodName": "CheckNSGConfigured",
      "Rationale":  "Restricting inbound and outbound traffic via NSGs limits the network exposure of the subnets within a virtual network and limits the attack surface.",
      "Recommendation": "Configure NSG rules to be as restrictive as possible via: (a) Azure Portal -> Network security groups -> <Your NSG> -> Inbound security rules -> Edit 'Allow' action rules. (b) Azure Portal -> Network security groups. -> <Your NSG> -> Outbound security rules -> Edit 'Allow' action rules.",
      "Tags": [
        "SDL",
        "Best Practice",
        "Automated",
        "NetSec"
      ],
      "Enabled": true,
      "DataObjectProperties": [
        "Name",
        "Properties"
      ]
    },
```

**Comment by Akreddy123** [comment]
Yes, it is possible to add custom policies. The steps to do so will be updated in the document soon.

**Comment by abhaydaga** [comment]
@spbreed We have documented the steps to add new controls to already extending SVT. Here is the documentation link:  https://github.com/azsk/DevOpsKit-docs/tree/master/08-Advanced-Features/Extending%20AzSK%20Module
