### ISSUE TITLE
Custom output folder for the ARMCheckerResult for the Get-AzSKARMTemplateSecurityStatus command

### ISSUE THREAD

**Issue by avi1479** [azsk/DevOpsKit-docs#159]
Hi,
This is a great tool to take the proactive decisions before deploying any unsafe resource to the cloud.
I am trying to use Get-AzSKARMTemplateSecurityStatus this command to automate the security checking for ARM templates. The thing that I observed after running this command is - the pattern of the output folder is fixed which is yyyymmdd_hhmmss.
My scenario here is running multiple security scans for ARM templates simultaneously. If I am running same command for multiple different ARM templates at the same time let's say 20181210_121212, then all the results will clash. To avoid this, if we could get the ability to rename/create custom folder for this result then it would be very helpful.

I am not sure if anybody needed this in the past, I am not using VSTS CI/CD pipeline right now, but using some other automation tool to automate the things, hence need this custom output folder name change.

Is it possible to get this done?

Thanks,
Avinash

**Comment by Khushboo-msft** [comment]
@avi1479 There's a very rare chance that the timestamp of execution will match exactly for the seconds part as well - hence the idea of appending the _hhmm**ss** to the file name was used.
We are currently focussed on including new features to the toolkit - not sure if this will be taken up anytime soon.
