### ISSUE TITLE
Incompatibility with the new AZ modules

### ISSUE THREAD

**Issue by ManuInNZ** [azsk/DevOpsKit-docs#176]
Hi

How to proceed with Install and Update if the module with the new Az module ?
```powershell
PS C:\WINDOWS\system32> Get-InstalledModule Az
```
Version | Name | Repository | Description
------- | ---- |  ---------- | -----------
1.0.1 | Az | PSGallery | Microsoft Azure PowerShell - Cmdlets to manage r...

Even with the Enable-AzureRMAlias the install will not proceed normally:
```powershell
PS C:\WINDOWS\system32> install-module azsk
PackageManagement\Install-Package : The following commands are already available on this
system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This module 'AzureRM.profile' may override the
existing commands. If you still want to install this module 'AzureRM.profile', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage
```

Any recommendations to be added to the FAQ?

Cheers

**Comment by Akreddy123** [comment]
@ManuInNZ: We are working on migrating DevOps Kit from AzureRM.* to the new Az.* modules. We expect to complete this user story over the next couple of sprints. Until then you will have to use DevOps Kit from an AzureRM environment.

**Comment by ManuInNZ** [comment]
Silly me but isn't it possible to use the AzureRM aliases and not have a
hard coded dependency on AzureRM.profile module presence?
E.g. testing for the existence of the key methods/functions required.

Cheers
Manu

**Comment by Khushboo-msft** [comment]
We have migrated the DevOps Kit to Az* modules from v.3.11.0 onwards. You can get the latest version (v 3.12.0) and try.
