### ISSUE TITLE
Enable_Diagnostics_Log controlIDs have some Ps issues  (i guess)

### ISSUE THREAD

**Issue by Crazyabout** [azsk/DevOpsKit-docs#182]
All the controls that fail on the Enable_Diagnostics_Log. Give the exception that the retention policy days must be at least 365 (or the number you give in ControlSettings : Diagnostics_RetentionPeriod_Min) and must be enabled.

But when i change the number in Controlsettings to 7 (just as an example) and my retention policy is set to 100 days it still fails . After some debugging i found out the retention policy *must* be set on the amount i set in ControlSettings. 

In the file ´C:\Program Files\WindowsPowerShell\Modules\AzSK\3.9.0\Framework\Abstracts\SVTBase` I found the Powershell method checkDiagnosticSetting whereby the code says 

`($_.RetentionPolicy.Days -eq $this.ControlSettings.Diagnostics_RetentionPeriod_Forever -or
											$_.RetentionPolicy.Days -eq $this.ControlSettings.Diagnostics_RetentionPeriod_Min))};`

I think the issue is whereby the function -eq is used . instead of equal or greater to create the situation 'at least  x days ' 
To change this inside my custom orginisation to my policy folder is somewhat of a challenge.
Can someone give me any help on this issue , Isn't it strange that the retention policy need all to be the same as the one in the ControlSettings , and that contradicts the error message "at least".

**Comment by Khushboo-msft** [comment]
I take it that you mean when the next release would be - That'd be around the mid of next month.

**Comment by Crazyabout** [comment]
Sorry typo
Thnx a lot , should i close this issue or keep it open (because the issue was not implemented yet)

**Comment by Khushboo-msft** [comment]
No worries.
You can close it after verifying.

**Comment by Khushboo-msft** [comment]
@Crazyabout This issue has been fixed in our latest release – v.3.11.0.
