### ISSUE TITLE
Programming Language Support

### ISSUE THREAD

**Issue by cheahengsoon** [azsk/DevOpsKit-docs#185]
Hi Team,
May I ask about currently Azure Secure DevOps Kit and Security intelligence Sense only Support C# only?
Any Roadmap for future improvement to support other programming language?

Thank You.

**Comment by abhaydaga** [comment]
@cheahengsoon : We do have plans to support Security Intelligence Sense for Visual Studio Code editor in the future, but we weren't able to prioritize it. We are curious to know for which language you would love to have SecIntel support.

**Comment by cheahengsoon** [comment]
I'm looking for Python. Because currently, I'm implementing Secure Coding Practice in my company and also Azure Secure DevOps Kit.
