### ISSUE TITLE
ARM Template checker covers not enough services

### ISSUE THREAD

**Issue by Crazyabout** [azsk/DevOpsKit-docs#187]
Is it on the road map to add services to the ARM template checker for the ARM template checker ?
It would be nice if the [list of services](https://github.com/azsk/DevOpsKit-docs/blob/master/03-Security-In-CICD/Readme.md#arm-template-checker---control-coverage) from the baseline controls are being upgraded to more Azure Services.

**Comment by abhaydaga** [comment]
@Crazyabout Few more Azure services are going to be added to the ARM Template checker in the next release.

**Comment by Crazyabout** [comment]
Can you provide me with more information about that release pls.
When is it going to be released ?
What 'few' services are going to be added to the list ?

**Comment by Khushboo-msft** [comment]
@Crazyabout 
The following services have been added to the list in our latest release – v.3.11.0:

- Key Vault
- Service Fabric
- Virtual Network
- Logic Apps
- Container Registry
