### ISSUE TITLE
Ubuntu 14.04, 18.04: Could not find a part of the path '/Microsoft/AzSK/AzSKSettings.json'

### ISSUE THREAD

**Issue by BharatRed** [azsk/DevOpsKit-docs#211]
We have installed DevOps Tools kit on Ubuntu 14.04, 18.04:
```
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Linux 3.13.0-163-generic #213-Ubuntu SMP Thu Nov 15 02:19:07 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
**Issue** When trying to execute one of the tool commands, for instance: 
`Get-AzSKAzureServicesSecurityStatus <subscription_id>`
It fails with the following reason:
`Could not find a part of the path '/Microsoft/AzSK/AzSKSettings.json'.`

There is a work around to this issue - to create the folders structure and the file manually. Then the command will start executing however in the end of the execution it fails again because a folder under /Microsoft/AzSK/timestamp to store logs and report does not exist.

**Comment by Khushboo-msft** [comment]
@BharatRed AzSK is not supported on Linux OS. The [Installation Guide](https://github.com/azsk/DevOpsKit-docs/blob/master/00a-Setup/Readme.md#installation-guide) should help.
