### ISSUE TITLE
Get-AzSKAzureDevOpsSecurityStatus not working, issue with parameter

### ISSUE THREAD

**Issue by jaguasch** [azsk/DevOpsKit-docs#246]
Trying to execute AzSK.AzureDevOps, but getting an error. It seems there is an issue with the OrganizationName parameter. 

**Get-Command -Module AzSK.AzureDevOps** version:
<pre>
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-AzSKAzureDevOpsSecurityStatus                  0.9.7      AzSK.AzureDevOps
Function        Set-AzSKAzureDevOpsPolicySettings                  0.9.7      AzSK.AzureDevOps
</pre>

Exception thrown, is like expecting a Subscription ID instead of an AzureDevops/VSTS organization name:

<pre>
PS C:\Users\user> Get-AzSKAzureDevOpsSecurityStatus

cmdlet Get-AzSKAzureDevOpsSecurityStatus at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
OrganizationName: ORGNAME
The type initializer for 'CommandHelper' threw an exception.
At C:\Users\user\Documents\WindowsPowerShell\Modules\AzSK.AzureDevOps\0.9.7\SVT\SVT.ps1:72 char:3
+         [CommandHelper]::BeginCommand($PSCmdlet.MyInvocation);
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException

Subscription Id [ORGNAME] is malformed. Subscription Id should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
At C:\Users\user\Documents\WindowsPowerShell\Modules\azsk\3.15.0\Framework\Abstracts\AzSKRoot.ps1:25 char:4
+             throw [SuppressedException] ("Subscription Id [$subscript ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], SuppressedException
    + FullyQualifiedErrorId : Subscription Id [ORGNAME] is malformed. Subscription Id should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

StackTrace: at AzSKRoot, C:\Users\user\Documents\WindowsPowerShell\Modules\azsk\3.15.0\Framework\Abstracts\AzSKRoot.ps1: line 25
at CommandBase, C:\Users\user\Documents\WindowsPowerShell\Modules\azsk\3.15.0\Framework\Abstracts\CommandBase.ps1: line 9
at SVTCommandBase, C:\Users\user\Documents\WindowsPowerShell\Modules\AzSK.AzureDevOps\0.9.7\Framework\Abstracts\SVTCommandBase.ps1: line 18
at ServicesSecurityStatus, C:\Users\user\Documents\WindowsPowerShell\Modules\AzSK.AzureDevOps\0.9.7\Framework\Core\SVT\ServicesSecurityStatus.ps1: line 5
at Get-AzSKAzureDevOpsSecurityStatus<Process>, C:\Users\user\Documents\WindowsPowerShell\Modules\AzSK.AzureDevOps\0.9.7\SVT\SVT.ps1: line 81
at <ScriptBlock>, <No file>: line 1
</pre>

**Comment by maykulkarni** [comment]
I believe you must have loaded `AzSK` and `AzSK.AzureDevOps` in the same session. You should open it in separate ones.

**Comment by jaguasch** [comment]
That was the issue thanks! Fresh session and:

> $ Import-module AzSK.AzureDevOps
> $ Get-AzSKAzureDevOpsSecurityStatus -OrganizationName
