### ISSUE TITLE
[Question] AzSK CA CentralSub mode - Fetch target subcriptions

### ISSUE THREAD

**Issue by DexterPOSH** [azsk/DevOpsKit-docs#248]
If I am using AzSK CA setup in a CentralSub mode. How do I gather information about all the subscriptions that are the Target subscriptions in the Central Mode?

I need this information to validate that all our Subscriptions are under CA.
I could locate that there is a file located in the StorageAccount\ca-multisubscan-config\TargetSubs.json  which contains the subscriptionIds, is this the source of truth for the target subscriptions?

**Comment by EvgeniaMartynova** [comment]
Hi,

You can get from: AzSK resource group, blob storage /ca-multisubscan-config/AzSKDev/TargetSubs.json

**Comment by DexterPOSH** [comment]
@EvgeniaMartynova Thanks for confirming it.
