### ISSUE TITLE
"Organization" misspelled as Organizaiton in multiple places

### ISSUE THREAD

**Issue by vhusker** [azsk/DevOpsKit-docs#251]
https://github.com/azsk/DevOpsKit-docs/blob/master/09-AzureDevOps(VSTS)-Security/ControlCoverage/Feature/Organizaiton.md

Also in the URL that the link goes to and on that documentation page.

**Comment by SINIKI** [comment]
Thank you for your feedback. This issue has been fixed. 
https://github.com/azsk/DevOpsKit-docs/pull/255
