### ISSUE TITLE
Advanced Features menu bar link broken

### ISSUE THREAD

**Issue by kiwi-cam** [azsk/DevOpsKit-docs#254]
When browsing the documentation at [https://azsk.azurewebsites.net/README.html](https://azsk.azurewebsites.net/README.html) the left hand menu bar includes a link labeled "Advanced Features". This link is pointed at **https://azsk.azurewebsites.net/08-Advanced-Features/Readme.md** which is invalid and results in the user recieving the error
`"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."`

08-Advanced-Features appears to have been renamed to 08-Miscellaneous-Features in GitHub but this link has not been updated.

**Comment by SINIKI** [comment]
Thank you for your feedback. This issue has been fixed. 
https://github.com/azsk/DevOpsKit-docs/pull/255
