### ISSUE TITLE
[Request] Change Get-AzSKAzureServicesSecurityStatus cmdlet name 

### ISSUE THREAD

**Issue by thuansoldier** [azsk/DevOpsKit-docs#27]
Normally `Get` is to retrieve status of something rather than an action. I'd like to propose to change the name of this cmdlet to `Run-AzSKAzureServiceSecurity` to give more sense. And we can have `Get-AzSKAzureServicesSecurityStatus` to return existing configuration of our security services (including specified resource group, storage account and other pre-configured settings).

**Comment by sbyna-msft** [comment]
@thuansoldier not sure which command you are referring to. Currently we don't have any command as Get-AzSKAzureServiceSecurity. We have two master get commands related to scanning, (a) 'Get-AzSKAzureServicesSecurityStatus' and, (b) 'Get-AzSKSubscriptionSecurityStatus' which returns security status of your azure services and subscription respectively. And also Run- is not a approved PS verb, usage of Run in the command will generate warning stating the same.
