### ISSUE TITLE
Report keeps on failing with "Do not allow inherited permission on build definitions" after fixing it

### ISSUE THREAD

**Issue by ankurkapoor** [azsk/DevOpsKit-docs#303]
Hi,

I am sure it could be something to do with permission i have setup for the script or in pipeline however i am unable to see the root cause and how to fix it. When i am running the below command, i keep getting same status report for the Builds even when i have fixed the permissions in AzDevOps for the listed builds (see the screenshot). Can you please help in suggesting what i could be doing wrong here?

`PS C:\WINDOWS\system32> Get-AzSKAzureDevOpsSecurityStatus -OrganizationName "MYORG" -ProjectNames "MYPROJECT" -BuildNames "*" -ReleaseNames "*" `                                       

Thanks!

**Below is the detailed log from the Build log file** ================================================================================
[AzureDevOps_Build_AuthZ_Disable_InheritPermissions]: Do not allow inherited permission on build definitions
--------------------------------------------------------------------------------
01/21/2020 16:20:27-Checking: [Build]-[Do not allow inherited permission on build definitions] for resource [deployment test]
Unable to verify inherit permission option. Please navigate to the your build pipeline and verify that inherit permission is disabled.

permissionSetId                : 33344d9c-fc72-4d6f-aba5-XXXXXXXX
token                          : 34966df1-1a08-41e9-b7c1-XXXXXXX/16
tokenDisplayName               : deployment test
canManageGroups                : True
canManagePermissions           : False
inheritPermissions             : False
controlManagesFocus            : True
canTokenInheritPermissions     : True
customDoNotHavePermissionsText : 
showAllGroupsIfCollection      : False
hideExplicitClearButton        : False
hideToolbar                    : False
allowAADSearchInHosted         : False

--------------------------------------------------------------------------------
**Failed**: [Build]-[Do not allow inherited permission on build definitions] for resource: [deployment test]
--------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/9979266/72823451-a8d63800-3c6b-11ea-8b75-20a4917d6f74.png)

**Comment by abhaydaga** [comment]
This issue is now fixed in the latest version - v.0.9.12
