### ISSUE TITLE
DevOpsKit-docs needs clarity on PAT token

### ISSUE THREAD

**Issue by larryclaman** [azsk/DevOpsKit-docs#321]
In the DevOpsKit doumentation file DevOpsKit-docs/09-AzureDevOps(VSTS)-Security/Readme.md, step 3 says: "Note: This task also requires Azure DevOps connection containing org details and PAT token to scan the required resources. Refer doc here to create token and provide it as part of connection"

Could you provide more details on the scope required for the personal access token? Does it need full access?  if not, which of Work Items, Code, Build, Release, etc does it need?  I'd prefer to grant it the least privs possible.

**Comment by abhaydaga** [comment]
Please find the list of scopes needed for PAT below:

Scope | Privilege | Remarks
-- | -- | --
Agent Pools | Read |  
Auditing | Read Audit Log |  
Build | Read |  
Entitlements | Read |  
Extensions | Read |  
Extension Data | Read & write | Write permissions reqd. to upload scan results to ext.   storage
Graph | Read |  
Identity | Read |  
Member Entitlement Management | Read |  
User Profile | Read |  
Project and Team | Read |  
Release | Read |  
Secure Files | Read |  
Service Connections | Read |  
Tokens | Read & manage | This is the only option available.
Variable Groups | Read |  

Please note that this list is based on the different artifacts the ADO security scanner module currently scans. Even if your PAT has a subset of above privileges, the module should gracefully handle and scan whatever it can using the token.

**Comment by AshishDadhich4h2** [comment]
@abhaydaga I followed above mentioned scopes of PAT with  ADO security scanner ADO task but publishes all the results in ADO dashboard except Organization Scan Results.  
![image](https://github.com/azsk/DevOpsKit-docs/assets/37674243/ec69859e-9fda-455c-9319-399f6438214c)

If I use PAT with full permissions, it works fine.

Not sure what specific permission is required for Organization Scan Results. I don't see any error in task log.
