### ISSUE TITLE
Getting issue when using this ARM Template "raw" uri in "Deploy to Azure" button

### ISSUE THREAD

**Issue by nli8n** [azsk/DevOpsKit-docs#375]
Getting issue when using this ARM Template "raw" uri in "Deploy to Azure" button :- 
Error parsing template. Please ensure template is valid JSON. Property name expected at character position 614. (1 other errors)

**Comment by v-soukum** [comment]
Thanks for reporting the issue.
We have validated and updated the ARM template.
