### ISSUE TITLE
problem with AzSK.AAD module

### ISSUE THREAD

**Issue by alllys** [azsk/DevOpsKit-docs#380]
Hi All.

I'm trying to check Azure AD security by using AzSK.AAD tool, but unfortunately can't run script.
After running 
>Get-AzSKAADSecurityStatusUser -TenantId "myid" -ObjectTypes All

I got an error:
The property 'ObjectId' cannot be found on this object. Verify that the property exists.
At C:\Users\login\Documents\WindowsPowerShell\Modules\AzSK.AAD\0.9.1\Framework\Helpers\AccountHelper.ps1:343 char:9
+         $uid = ([AccountHelper]::GetCurrentAADUserObject()).ObjectId
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Do you have any ideas how to deal with this issue?

**Comment by ritika-msft** [comment]
This issue was responded in external support. Therefore closing this issue.
