### ISSUE TITLE
Find-AzureRMResource is no longer used in Azurerm.resources, replaced by Get-AzureRMResource

### ISSUE THREAD

**Issue by brwilkinson** [azsk/DevOpsKit-docs#63]
if possible please update references from Find-AzureRMResource to Get-AzureRMResource

or just add the alias:

new-alias -Name find-azurermresource -Value Get-AzureRmResource

This was updated in AzureRM v6.0 +
https://github.com/Azure/azure-powershell/releases/tag/v6.0.0-May2018

Not sure if the later azurerm modules are supported, however I prefer to use the latest azurerm modules, so this is a workaround. . . 

e.g. the following works fine after updating the modules, then adding the alias back.

Get-AzSKInfo -InfoType SubscriptionInfo -SubscriptionId xyz

**Comment by VishalHaibatpure** [comment]
Please consider [this](https://github.com/azsk/DevOpsKit-docs/blob/master/00a-Setup/Readme.md#when-will-azsk-support-the-newest-azurerm-module-currently-5x-can-i-run-both-side-by-side-in-the-meantime-what-if-i-need-to-run-both-azsk-and-the-new-version-of-azurerm-for-different-tasks) FAQ to run AzSK with multiple AzureRM modules versions present on machine. We will soon update reference to latest AzureRM.
