### ISSUE TITLE
Getting error "The specified module 'AzSK' was not loaded because no valid module file was found in any module directory" since last week

### ISSUE THREAD

**Issue by SahinOzdemir** [azsk/DevOpsKit-docs#82]
Hi,
Since last week, all of a sudden the SVT task in our release is giving the error "The specified module 'AzSK' was not loaded because no valid module file was found in any module directory" out of nothing. I have read the FAQ which is mentioning this issue and disabled the checkbox as mentioned. 
Nevertheless the issue stil exists. 

I also tried to delete the task in all build agents on our build server, it downloads the task again when a release is kicked of, but it ends up in the same issue.

Does anyone have an idea on how to resolve this issue when using your own build server w. agents?

**Comment by SahinOzdemir** [comment]
Hi, Just ran the command on the buildserver and this is the output. Please let me know how to move forward.

C:\Users\<USERNAME>\Documents\WindowsPowerShell\Modules;
C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;
C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\;
C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\7.2.14544.0

**Comment by VishalHaibatpure** [comment]
Can you try cleaning up Module folder (take back at other place if you need it later) and rerunning task. CICD task will install latest AzSK with AzureRM dependencies.
