### ISSUE TITLE
Support for V2 Storage accounts

### ISSUE THREAD

**Issue by wendellh3** [azsk/DevOpsKit-docs#83]
I am evaluating the AzSK for my enterprise.  During an initial pass using the ARMTemplateChecker, I discovered that my V2 storage account in the ARM template are ignored.  Will this be supported in the near future?  Thanks!

**Comment by VishalHaibatpure** [comment]
Thanks for feedback. We will be updating ARM template checker for V2 Storage account soon.

**Comment by VishalHaibatpure** [comment]
Can you run ARM template checker. Storage V2 check enabled in latest AzSK version 3.5.0
