### ISSUE TITLE
Links in homepage of azsk.azurewebsites.net not accessible

### ISSUE THREAD

**Issue by GuruCharan94** [azsk/DevOpsKit-docs#84]
![secure devops kit for azure](https://user-images.githubusercontent.com/21144140/44097550-a54061e2-9ffb-11e8-80d3-396b39df043f.png)

https://azsk.azurewebsites.net/ 

The three links under the get started section are not clickable. 
F12 on chrome indicates that the "What's New" text in the next div is messing with the layout.
The links work fine on deleting the "What's new" part.

**Comment by v-zhgup** [comment]
Thanks for pointing out.
Please check now, the issue has been fixed.
